title: "Thomas de Laubier"
description: "Data Scientist & AI Engineer | M2 MAS (Data Science & IA) - Université Rennes 2"
url: "https://thomas-delaubier.fr"
theme: jekyll-theme-cayman
show_downloads: false
markdown: kramdown
lang: "fr"
